import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class HeroeslocalService {

    Herois: any = [{ "response": "success", "id": "70", "name": "Batman", "powerstats": { "intelligence": "100", "strength": "26", "speed": "27", "durability": "50", "power": "47", "combat": "100" }, "biography": { "full-name": "Bruce Wayne", "alter-egos": "No alter egos found.", "aliases": [ "Insider", "Matches Malone" ], "place-of-birth": "Crest Hill, Bristol Township; Gotham County", "first-appearance": "Detective Comics #27", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Humano", "height": [ "6'2", "188 cm" ], "weight": [ "210 lb", "95 kg" ], "eye-color": "blue", "hair-color": "black" }, "work": { "occupation": "Businessman", "base": "Batcave, Stately Wayne Manor, Gotham City; Hall of Justice, Justice League Watchtower" }, "connections": { "group-affiliation": "Batman Family, Batman Incorporated, Justice League, Outsiders, Wayne Enterprises, Club of Heroes, formerly White Lantern Corps, Sinestro Corps", "relatives": "Damian Wayne (son), Dick Grayson (adopted son), Tim Drake (adopted son), Jason Todd (adopted son), Cassandra Cain (adopted ward)\nMartha Wayne (mother, deceased), Thomas Wayne (father, deceased), Alfred Pennyworth (former guardian), Roderick Kane (grandfather, deceased), Elizabeth Kane (grandmother, deceased), Nathan Kane (uncle, deceased), Simon Hurt (ancestor), Wayne Family" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/639.jpg" } }
    ,
    { "response": "success", "id": "644", "name": "Superman", "powerstats": { "intelligence": "94", "strength": "100", "speed": "100", "durability": "100", "power": "100", "combat": "85" }, "biography": { "full-name": "Clark Kent", "alter-egos": "Superman Prime One-Million", "aliases": [ "Clark Joseph Kent", "The Man of Steel", "the Man of Tomorrow", "the Last Son of Krypton", "Big Blue", "the Metropolis Marvel", "the Action Ace" ], "place-of-birth": "Krypton", "first-appearance": "ACTION COMICS #1", "publisher": "Superman Prime One-Million", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Kryptoniano", "height": [ "6'3", "191 cm" ], "weight": [ "225 lb", "101 kg" ], "eye-color": "Blue", "hair-color": "Black" }, "work": { "occupation": "Reporter for the Daily Planet and novelist", "base": "Metropolis" }, "connections": { "group-affiliation": "Justice League of America, The Legion of Super-Heroes (pre-Crisis as Superboy); Justice Society of America (pre-Crisis Earth-2 version); All-Star Squadron (pre-Crisis Earth-2 version)", "relatives": "Lois Lane (wife), Jor-El (father, deceased), Lara (mother, deceased), Jonathan Kent (adoptive father), Martha Kent (adoptive mother), Seyg-El (paternal grandfather, deceased), Zor-El (uncle, deceased), Alura (aunt, deceased), Supergirl (Kara Zor-El, cousin), Superboy (Kon-El/Conner Kent, partial clone)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/791.jpg" } }
    ,
    { "response": "success", "id": "720", "name": "Wonder Woman", "powerstats": { "intelligence": "88", "strength": "100", "speed": "79", "durability": "100", "power": "100", "combat": "100" }, "biography": { "full-name": "Diana Prince", "alter-egos": "No alter egos found.", "aliases": [ "Princess Diana", "Princess of the Amazons", "Goddess of Truth", " Wondy", "Wonder Girl", "The Amazon Princess" ], "place-of-birth": "Themyscira", "first-appearance": "All-Star Comics #8 (December, 1941)", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Female", "race": "Amazona", "height": [ "6'0", "183 cm" ], "weight": [ "165 lb", "74 kg" ], "eye-color": "Blue", "hair-color": "Black" }, "work": { "occupation": "Adventurer, Emissary to the world of Man, Protector of Paradise Island; former Goddess of Truth", "base": "-" }, "connections": { "group-affiliation": "Justice League of America, Justice Society of America (pre-Crisis Earth-2 version); All-Star Squadron (pre-Crisis Earth-2 version)", "relatives": "Queen Hippolyta (mother, deceased), Donna Troy (Troia) (magically-created duplicate)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/807.jpg" } }
    ,
    { "response": "success", "id": "265", "name": "Flash", "powerstats": { "intelligence": "88", "strength": "48", "speed": "100", "durability": "60", "power": "100", "combat": "60" }, "biography": { "full-name": "Barry Allen", "alter-egos": "Black Racer", "aliases": [ "The Scarlet Speedster", "the Fastest Man Alive", "the Monarch of Motion", "the Sultan of Speed" ], "place-of-birth": "Fallville, Iowa", "first-appearance": "Showcase #4 (October, 1956)", "publisher": "Black Racer", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Metahumano", "height": [ "6'0", "183 cm" ], "weight": [ "195 lb", "88 kg" ], "eye-color": "Blue", "hair-color": "Blond" }, "work": { "occupation": "Forensic Scientist", "base": "Central City, Missouri" }, "connections": { "group-affiliation": "Flash Family, Justice League of America; formerly Blue Lantern Corps", "relatives": "Henry and Nora (parents), Malcolm Thawne (twin), Iris West Allen (wife), Wally West (Flash III, nephew), Don and Dawn Allen (son and daughter), Bart Allen (Flash IV, grandson), Jenni Ognats (granddaughter)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/892.jpg" } }
  ,
  { "response": "success", "id": "306", "name": "Green Lantern", "powerstats": { "intelligence": "69", "strength": "90", "speed": "75", "durability": "80", "power": "100", "combat": "70" }, "biography": { "full-name": "Hal Jordan", "alter-egos": "No alter egos found.", "aliases": [ "Parallax", "Spectre", "Green Lantern" ], "place-of-birth": "Coast City, California", "first-appearance": "Showcase #22", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Humano", "height": [ "6'2", "188 cm" ], "weight": [ "200 lb", "90 kg" ], "eye-color": "Brown", "hair-color": "Brown" }, "work": { "occupation": "Adventurer, Air Force Test Pilot", "base": "-" }, "connections": { "group-affiliation": "Green Lantern Corps, Justice League of America, Justice League Europe, frequently teamed with the second Flash and the original Green Arrow", "relatives": "Martin H. \"Marty\" Jordan (father, deceased), Jessica Jordan (mother, deceased), Jim Jordan (younger brother), Jack Jordan (older brother, deceased), Jan Jordan (sister-in-law, deceased), Helen Jordan (neice), Larry Jordan (Air Wave I - cousin, deceased), Hal Jordan (Air Wave II - cousin)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/697.jpg" } }
  ,
  { "response": "success", "id": "156", "name": "Captain Marvel", "powerstats": { "intelligence": "88", "strength": "100", "speed": "88", "durability": "95", "power": "100", "combat": "75" }, "biography": { "full-name": "Billy Batson", "alter-egos": "No alter egos found.", "aliases": [ "The World's Mightiest Mortal", "The Big Red Cheese", "Captain Thunder", "Shazam" ], "place-of-birth": "Fawcett City, United States", "first-appearance": "Whiz Comics no. 2 (1940)", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Humano", "height": [ "6'4", "193 cm" ], "weight": [ "225 lb", "101 kg" ], "eye-color": "Blue", "hair-color": "Black" }, "work": { "occupation": "-", "base": "-" }, "connections": { "group-affiliation": "Marvel Family, Justice Society of America", "relatives": "C.C. Batson (father, deceased), Marilyn Batson (mother, deceased), Ebenezer Batson (uncle), Mary Batson (Mary Marvel, sister)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/278.jpg" } }
  ,
  { "response": "success", "id": "432", "name": "Martian Manhunter", "powerstats": { "intelligence": "100", "strength": "95", "speed": "92", "durability": "100", "power": "100", "combat": "85" }, "biography": { "full-name": "J'onn J'onzz", "alter-egos": "No alter egos found.", "aliases": [ "ohn Jones; J'Onn J'Onzz (alternate spelling); Big Green Buddy; J.J.; Jolly Green Giant; Light to the Light; Manhunter; Manhunter from Mars; Son of Mars; Bronze Wraith", "Bloodwynd", "many others" ], "place-of-birth": "-", "first-appearance": "Detective Comics #225 (1955)", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Marciano", "height": [ "6'7", "201 cm" ], "weight": [ "300 lb", "135 kg" ], "eye-color": "Red", "hair-color": "No Hair" }, "work": { "occupation": "-", "base": "-" }, "connections": { "group-affiliation": "Darkstars, Justice League of Aliens, Justice League Of America, Justice League Task Force, Justice League Unlimited, Martians, Outsiders", "relatives": "M'yrnn J'onzz (father, deceased); Sha'sheen J'onzz (mother, deceased); M'yri'ah (wife, deceased); K'hym (daughter, deceased); Ma'alefa'ak (twin brother); D'all (father-in-law, deceased); J'ahrl J'onzz (ancestor, deceased)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/733.jpg" } }
  ,
  { "response": "success", "id": "28", "name": "Animal Man", "powerstats": { "intelligence": "56", "strength": "48", "speed": "47", "durability": "85", "power": "73", "combat": "80" }, "biography": { "full-name": "Bernhard Baker", "alter-egos": "No alter egos found.", "aliases": [ "The Human Zoo; A-Man; The Man with Animal Powers" ], "place-of-birth": "-", "first-appearance": "Strange Adventures #180 (September, 1965)", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Humano", "height": [ "6'0", "183 cm" ], "weight": [ "185 lb", "83 kg" ], "eye-color": "Blue", "hair-color": "Blond" }, "work": { "occupation": "-", "base": "San Diego, California" }, "connections": { "group-affiliation": "Formerly Animal Masters, Forgotten Heroes, Justice League of America, Justice League Europe", "relatives": "Ellen Frazier (wife), Cliff Baker (son), Maxine Baker (daughter), unnamed second daughter, Frank Baker, Jr. (father), Phyllis Baker (mother), unnamed sister, Frank, Sr (grandfather), Teddy (great grandfather), Sherman (great-great grandfather), Jack (great-great-great grandfather), Mary Frazier (mother-in-law), Dudley (uncle-in-law), Annie Cassidy (mother of second daughter), Lucy Cassidy (half-sister of second daughter)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/632.jpg" } }
  ,
  { "response": "success", "id": "730", "name": "Zatanna", "powerstats": { "intelligence": "81", "strength": "10", "speed": "23", "durability": "28", "power": "100", "combat": "56" }, "biography": { "full-name": "Zatanna Zatara", "alter-egos": "No alter egos found.", "aliases": [ "-" ], "place-of-birth": "-", "first-appearance": "Hawkman #4", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Female", "race": "Humana", "height": [ "5'7", "170 cm" ], "weight": [ "127 lb", "57 kg" ], "eye-color": "Blue", "hair-color": "Black" }, "work": { "occupation": "-", "base": "-" }, "connections": { "group-affiliation": "Misty Kilgore, Seven Soldiers of Victory, Justice League, Sentinels of Magic", "relatives": "Giovanni \"John\" Zatara (father, deceased), Sindella (mother, deceased), Leonardo da Vinci (paternal ancestor, deceased)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/809.jpg" } }
  ,
  { "response": "success", "id": "368", "name": "Green Lantern", "powerstats": { "intelligence": "56", "strength": "85", "speed": "42", "durability": "64", "power": "100", "combat": "65" }, "biography": { "full-name": "John Stewart", "alter-egos": "No alter egos found.", "aliases": [ "Green Lantern" ], "place-of-birth": "-", "first-appearance": "Green Lantern Vol 2 #87", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Humano", "height": [ "6'1", "185 cm" ], "weight": [ "201 lb", "90 kg" ], "eye-color": "Green", "hair-color": "Black" }, "work": { "occupation": "Architect", "base": "Detroit, Michigan · Oa · formerly New York City" }, "connections": { "group-affiliation": "Green Lantern Corps, formerly Justice League of America, Darkstars", "relatives": "Roy Stewart (grandfather, deceased), Addie Stewart (grandmother, deceased), Loretta Stewart (aunt, deceased), Katma Tui (wife, deceased)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/873.jpg" } }
  ,
  { "response": "success", "id": "367", "name": "Constantine", "powerstats": { "intelligence": "90", "strength": "8", "speed": "8", "durability": "30", "power": "100", "combat": "55" }, "biography": { "full-name": "John Constantine", "alter-egos": "No alter egos found.", "aliases": [ "Hellblazer" ], "place-of-birth": "-", "first-appearance": "Swamp Thing Vol 2 #37 (June, 1985)", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Humano", "height": [ "6'0", "183 cm" ], "weight": [ "- lb", "74 kg" ], "eye-color": "Blue", "hair-color": "Blond" }, "work": { "occupation": "-", "base": "-" }, "connections": { "group-affiliation": "Justice League Dark, Justice League", "relatives": "Thomas Constantine (father, deceased), Cheryl Constantine (sister, deceased)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/718.jpg" } }
  ,
  { "response": "success", "id": "491", "name": "Nightwing", "powerstats": { "intelligence": "88", "strength": "11", "speed": "33", "durability": "28", "power": "36", "combat": "100" }, "biography": { "full-name": "Dick Grayson", "alter-egos": "Batman II, Robin", "aliases": [ "Freddie Dinardo", "Freddy Loyd", "The Target", "Renegade", "The Worlds Greatest Acrobat", "The Aerial Avenger", "Pixie Boots", "The Boy / Teen Wonder", "The Worlds Greatest Detective", "The Caped Crusader" ], "place-of-birth": "Gotham City", "first-appearance": "as Dick Grayson and Robin) Detective Comics #38, (as Nightwing) Tales of the Teen Titans #44, (as Batman) Batman #512", "publisher": "Batman II", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Humano", "height": [ "5'10", "178 cm" ], "weight": [ "175 lb", "79 kg" ], "eye-color": "Blue", "hair-color": "Black" }, "work": { "occupation": "Vigilante and detective, former police officer, former Circus Acrobat", "base": "Wayne Tower, Gotham City; formerly the Batcave; formerly Bludhaven; formerly New York City" }, "connections": { "group-affiliation": "Batman Family and the JLA; formerly the Teen Titans, the New Titans, the Titans and the Outsiders", "relatives": "John Grayson (father, deceased), Mary Grayson (mother, deceased), Bruce Wayne / Batman (adoptive father), Damian Wayne / Robin (foster brother), Jason Todd / Red Hood (adoptive brother), Tim Drake / Red Robin (adoptive brother), Cassandra Cain / Batgirl IV (adoptive sister)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/851.jpg" } }
  ,
  { "response": "success", "id": "53", "name": "Atom II", "powerstats": { "intelligence": "88", "strength": "10", "speed": "33", "durability": "45", "power": "40", "combat": "60" }, "biography": { "full-name": "Ray Palmer", "alter-egos": "No alter egos found.", "aliases": [ "The Mighty Mite", "the Tiny Titan", "the World's Smallest Hero" ], "place-of-birth": "-", "first-appearance": "Showcase #34", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Humano", "height": [ "6'0", "183 cm" ], "weight": [ "180 lb", "81 kg" ], "eye-color": "Brown", "hair-color": "Auburn" }, "work": { "occupation": "Physics Professor", "base": "Ivy Town" }, "connections": { "group-affiliation": "Justice League of America, formerly; Suicide Squad, Teen Titans", "relatives": "Jean Loring (ex-wife, deceased), Princess Laethwen (wife, deceased), Danny Palmer (brother, deceased), David Palmer (father), Susan Palmer (mother, deceased), David Palmer (uncle)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/938.jpg" } }
  ,
  { "response": "success", "id": "97", "name": "Black Canary", "powerstats": { "intelligence": "68", "strength": "10", "speed": "33", "durability": "20", "power": "52", "combat": "90" }, "biography": { "full-name": "Laurel Lance", "alter-egos": "No alter egos found.", "aliases": [ "Dinah Laurel Lance Queen; Dinah Laurel Lance-Windrow" ], "place-of-birth": "-", "first-appearance": "Justice League of America (Volume 1) #75", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Female", "race": "Metahumana", "height": [ "5'7", "170 cm" ], "weight": [ "130 lb", "59 kg" ], "eye-color": "Blue", "hair-color": "Blond" }, "work": { "occupation": "Detective/Crime-fighter, Chairperson of the Justice League of America; former florist, judo instructor", "base": "Formerly Oracle's clock tower in Gotham City; formerly Seattle, Washington; formerly Star City, California; formerly New York City, New York (as a member of the JSA); currently mobile" }, "connections": { "group-affiliation": "Birds of Prey; formerly Justice League of America, Justice Society of America, Justice League Task Force, Justice League International, Team Arrow", "relatives": "Larry Lance (father, deceased), Dinah Drake Lance (Black Canary, mother, deceased); Oliver Queen (Green Arrow, husband); Craig Windrow (ex-husband); Sin (adoptive daughter)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/1005.jpg" } }
  ,
  { "response": "success", "id": "298", "name": "Green Arrow", "powerstats": { "intelligence": "81", "strength": "12", "speed": "35", "durability": "28", "power": "39", "combat": "90" }, "biography": { "full-name": "Oliver Queen", "alter-egos": "No alter egos found.", "aliases": [ "The Emerald Archer", "Battling Bowman" ], "place-of-birth": "-", "first-appearance": "More Fun Comics #73 (November 1941)", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Humano", "height": [ "6'2", "188 cm" ], "weight": [ "195 lb", "88 kg" ], "eye-color": "Green", "hair-color": "Blond" }, "work": { "occupation": "Professional Crime-fighter; Multi-Billionaire", "base": "Star City, California; Formerly Seattle, Washington" }, "connections": { "group-affiliation": "Justice League Reserve, Connor Hawke, Mia Dearden, Arsenal, Green Arrows of the World, Black Canary, Green Lantern Hal Jordan, Shado, Eddie Fyers, Justice League Elite, Seven Soldiers of Victory, All-Star Squadron", "relatives": "Conner Hawke (son); Robert (son); Cissie King (possible daughter); Roy Harper - Red Arrow (adoptive son); Dinah Laurel Lance (wife); Dinah Drake Lance (mother-in-law, deceased); Larry Lance (father-in-law, deceased)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/696.jpg" } }
  ,
  { "response": "success", "id": "316", "name": "Hawkman", "powerstats": { "intelligence": "80", "strength": "66", "speed": "25", "durability": "65", "power": "55", "combat": "80" }, "biography": { "full-name": "Carter Hall", "alter-egos": "No alter egos found.", "aliases": [ "-" ], "place-of-birth": "-", "first-appearance": "FLASH COMICS #1 (January 1940)", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Humano", "height": [ "6'1", "185 cm" ], "weight": [ "195 lb", "88 kg" ], "eye-color": "Blue", "hair-color": "Brown" }, "work": { "occupation": "Adventurer", "base": "-" }, "connections": { "group-affiliation": "Justice Society of America, Justice League of America, All-Star Squadron", "relatives": "Shiera Sanders Hall (wife, deceased; soul currently inhabiting the body of Kendra Saunders), Hector Hall (son, deceased), Daniel Hall (grandson), Lyta Trevor Hall (daughter-in-law, deceased)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/839.jpg" } }
  ,
  { "response": "success", "id": "315", "name": "Hawkgirl", "powerstats": { "intelligence": "50", "strength": "28", "speed": "53", "durability": "99", "power": "96", "combat": "72" }, "biography": { "full-name": "Kendra Saunders", "alter-egos": "No alter egos found.", "aliases": [ "Chay-Ara; Sheila Carr; Lady Celia Penbrook", "Kate Manser; Shiera Sanders" ], "place-of-birth": "-", "first-appearance": "JSA Secret Files #1 (August 1999)", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Female", "race": "Humana", "height": [ "5'9", "175 cm" ], "weight": [ "135 lb", "61 kg" ], "eye-color": "Green", "hair-color": "Red" }, "work": { "occupation": "Adventurer, Film School Student, Temp Curator of the Stonechat Museum", "base": "St. Roch, Louisiana, JLA Watchtower; formerly Manhattan, New York (as a member of the JSA)" }, "connections": { "group-affiliation": "Justice League of America, formerly a member of the JSA, Birds of Prey", "relatives": "Michael Saunders (father, deceased); Trina Saunders (mother, deceased); Cyril \"Speed\" Saunders (grandfather); Mia Saunders (daughter); Shiera Hall (Hawkgirl, great-aunt, deceased); Carter Hall (Hawkman, great-uncle); Hector Hall (Dr. Fate, 2nd cousin); Northwind (cousin through adoption); Hippolyta Hall (Fury, cousin through marriage); Sandman (Daniel Hall, 3rd cousin), Death, Destiny, Destruction, Delirium, Desire (3rd cousins)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/703.jpg" } }
  ,
  { "response": "success", "id": "699", "name": "Vixen", "powerstats": { "intelligence": "50", "strength": "38", "speed": "50", "durability": "50", "power": "62", "combat": "25" }, "biography": { "full-name": "Mari McCabe", "alter-egos": "No alter egos found.", "aliases": [ "-" ], "place-of-birth": "Zambesi", "first-appearance": "Action Comics #521 (July, 1981)", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Female", "race": "Humana", "height": [ "5'9", "175 cm" ], "weight": [ "140 lb", "63 kg" ], "eye-color": "Amber", "hair-color": "Black" }, "work": { "occupation": "Former Model", "base": "-" }, "connections": { "group-affiliation": "Formerly Suicide Squad, Checkmate, Ultramarines, Birds of Prey, Justice League of America", "relatives": "Reverend Richard Jiwe (father, deceased), Jeanne-Mari Jiwe (mother, deceased), General Mustapha Maksai (uncle, deceased), Tantu (ancestor)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/10109.jpg" } }
  ,
  { "response": "success", "id": "535", "name": "Question", "powerstats": { "intelligence": "81", "strength": "14", "speed": "27", "durability": "35", "power": "20", "combat": "80" }, "biography": { "full-name": "Charles Victor Szasz", "alter-egos": "No alter egos found.", "aliases": [ "Vic Sage" ], "place-of-birth": "-", "first-appearance": "Blue Beetle (Charlton) Vol 4 #1 (June, 1967)", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Humano", "height": [ "6'2", "188 cm" ], "weight": [ "185 lb", "83 kg" ], "eye-color": "Blue", "hair-color": "Blond" }, "work": { "occupation": "Former Television Investigative Journalist", "base": "Hub City; Chicago, Gotham City, Metropolis" }, "connections": { "group-affiliation": "Formerly L.A.W., JLA, Black Lantern Corps", "relatives": "-" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/760.jpg" } }
  ,
  { "response": "success", "id": "63", "name": "Batgirl", "powerstats": { "intelligence": "88", "strength": "11", "speed": "33", "durability": "40", "power": "34", "combat": "90" }, "biography": { "full-name": "Barbara Gordon", "alter-egos": "Oracle", "aliases": [ "Oracle", "Bluebelle" ], "place-of-birth": "-", "first-appearance": "Detective Comics #359", "publisher": "Oracle", "alignment": "good" }, "appearance": { "gender": "Female", "race": "Humana", "height": [ "5'7", "170 cm" ], "weight": [ "126 lb", "57 kg" ], "eye-color": "Green", "hair-color": "Red" }, "work": { "occupation": "-", "base": "Gotham City, formerly Metropolis, Platinum Flats" }, "connections": { "group-affiliation": "-", "relatives": "James Gordon (father) � Barbara Eileen (mother) � James Gordon, Jr. (brother)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/1111.jpg" } }
  ,
  { "response": "success", "id": "66", "name": "Batgirl IV", "powerstats": { "intelligence": "69", "strength": "12", "speed": "27", "durability": "56", "power": "46", "combat": "100" }, "biography": { "full-name": "Cassandra Cain", "alter-egos": "No alter egos found.", "aliases": [ "Kasumi", "various mundane persona," ], "place-of-birth": "League of Assassins (exact base is unknown)", "first-appearance": "Batman: Legends of the Dark Knight #120", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Female", "race": "Humana", "height": [ "5'5", "165 cm" ], "weight": [ "115 lb", "52 kg" ], "eye-color": "Green", "hair-color": "Black" }, "work": { "occupation": "-", "base": "Gotham City; Bl�dhaven; Tibet; New York City" }, "connections": { "group-affiliation": "Titans East, League of Assassins, Batman Family, Justice League Elite, Young Justice", "relatives": "David Cain (father), Lady Shiva (mother), Carolyn (aunt, deceased), Annalea (sibling, deceased), 'The Mad Dog' (sibling)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/1113.jpg" } }
  ,
  { "response": "success", "id": "542", "name": "Raven", "powerstats": { "intelligence": "50", "strength": "10", "speed": "29", "durability": "70", "power": "84", "combat": "40" }, "biography": { "full-name": "Rachel Roth", "alter-egos": "No alter egos found.", "aliases": [ "Pride", "Dark Raven" ], "place-of-birth": "Azarath", "first-appearance": "DC Comics Presents #26 (October, 1980)", "publisher": "DC Comics", "alignment": "neutral" }, "appearance": { "gender": "Female", "race": "Humana", "height": [ "5'5", "165 cm" ], "weight": [ "110 lb", "50 kg" ], "eye-color": "Indigo", "hair-color": "Black" }, "work": { "occupation": "Adventurer, high school student", "base": "-" }, "connections": { "group-affiliation": "Teen Titans, formerly Sentinels of Magic", "relatives": "Trigon (father), Angela Roth (mother, deceased), Gluttony, Greed, Lust, Wrath, Envy, Sloth (half-brothers, status unknown)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/764.jpg" } }
  ,
  { "response": "success", "id": "551", "name": "Red Tornado", "powerstats": { "intelligence": "75", "strength": "38", "speed": "67", "durability": "60", "power": "100", "combat": "40" }, "biography": { "full-name": "John Smith", "alter-egos": "No alter egos found.", "aliases": [ "Ulthoon", "Tornado Tyrant of Rann", "Tornado Champion", "Tornado Man Dreaming", "\"Reddy\"" ], "place-of-birth": "-", "first-appearance": "As Red Tornado: Justice League of America #64, As Ulthoon: Mystery in Space #61", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Andróide", "height": [ "6'1", "185 cm" ], "weight": [ "325 lb", "146 kg" ], "eye-color": "Green", "hair-color": "No Hair" }, "work": { "occupation": "-", "base": "Happy Harbor, Rhode Island" }, "connections": { "group-affiliation": "Justice League of America, formerly Parliament of Vapors, T.O. Morrow, Justice Society of America, Young Justice, Primal Force, Leymen, Donna Troy", "relatives": "T.O. Morrow (creator/father),Red Volcano (brother; deceased), Red Inferno (brother; deceased), Red Torpedo (sister; deceased), Tomorrow Woman (\"sister\"), Kathy Sutton (wife), Traya Sutton (adoptive daughter)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/1149.jpg" } }
  ,
  { "response": "success", "id": "194", "name": "Cyborg", "powerstats": { "intelligence": "75", "strength": "53", "speed": "42", "durability": "85", "power": "71", "combat": "64" }, "biography": { "full-name": "Victor Stone", "alter-egos": "No alter egos found.", "aliases": [ "Cyberion Technis", "Omegadrome", "Planet Cyberion" ], "place-of-birth": "New York City, New York", "first-appearance": "DC Comics Presents #26 (October, 1980)", "publisher": "DC Comics", "alignment": "good" }, "appearance": { "gender": "Male", "race": "Cyborg", "height": [ "6'6", "198 cm" ], "weight": [ "385 lb", "173 kg" ], "eye-color": "Brown", "hair-color": "Black" }, "work": { "occupation": "Adventurer, Teen Titan", "base": "San Francisco" }, "connections": { "group-affiliation": "Justice League; formerly Teen Titans, Titans, Titans East, New Teen Titans", "relatives": "Silas Stone (father), Elinore Stone (mother), Tucker Stone (grandfather), Maude Stone (grandmother)" }, "image": { "url": "https://www.superherodb.com/pictures2/portraits/10/100/1204.jpg" } }
]
  
  constructor() { }

  getHeroisLocal (valor){
    return this.Herois [valor];
  }

}
